### PR TITLE
Add LICENSE file (GPLv3)

### PR DESCRIPTION
**Pull request by cherylli**
Just using the github built-in GPL v3

|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**195**](https://github.com/MarianaSouza/web-dev-path/issues/195) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
yes

#### What is this change?
Add a GPLv3 license

#### Were there any complications while making this change?
no

#### When should this be merged?
after review

### CODE REVIEW

**Comment by mariana-caldas** [comment]
Thanks so much for doing this, @cherylli !

Could you please also add the following?

1. update our `package.json` file by adding the "license" property at the root level on the JSON structure like in this example?

```
{
  "name": "web-dev-path",
  "version": "1.3.0",
  "private": true,
  "scripts": {
    "dev": "yarn run open-browser-win && next dev -p 3010",
    "dev-mac": "yarn run open-browser-mac && next dev -p 3010",
    "open-browser-win": "start http://localhost:3010",
    "open-browser-mac": "open http://localhost:3010",
    "build": "next build",
    "start": "next start",
    "lint": "prettier --check .",
    "format": "prettier --write .",
    "prepare": "husky install"
  },
  "lint-staged": {
    "**/*.{js,jsx,ts,tsx,scss}": [
      "prettier --write"
    ]
  },
  "dependencies": {
    "@sendgrid/mail": "^7.7.0",
    "html-entities": "^2.3.2",
    "next": "13.4.19",
    "next-pwa": "^5.6.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-google-recaptcha": "^2.1.0",
    "react-hook-form": "^7.35.0",
    "react-mailchimp-subscribe": "^2.1.3",
    "sass": "^1.35.1",
    "styled-components": "^5.3.6",
    "swiper": "^8.2.2"
  },
  "devDependencies": {
    "husky": "^8.0.0",
    "lint-staged": "^13.0.3",
    "prettier": "^2.7.1",
    "prettylint": "^1.0.0",
    "webpack": "^5.88.1"
  },
  "resolutions": {
    "styled-components": "^5"
  },
  "license": "GPL-3.0"
}
```

2. Update the README by creating this section at the bottom of the document. Please add a link to the file.

```
## License

This project is licensed under the GNU General Public License v3.0 - see the [LICENSE](LICENSE) file for details.
```

**Review by Satoshi-Sh — APPROVED** [review]
Looks nice. PR will be good to go after incorporating Mariana's suggestion.

Do we need to add a code of conduct too?

**Comment by cherylli** [comment]
> Looks nice. PR will be good to go after incorporating Mariana's suggestion.
> 
> Do we need to add a code of conduct too?

thanks, I believe Mariana is looking at it.

> This project is licensed under the GNU General Public License v3.0 - see the [LICENSE](LICENSE) file for details.

updated readme. looks like the link works fine as it is.

**Review by mariana-caldas — APPROVED** [review]
Thanks so much, @cherylli !

**Pull request merged**
