### PR TITLE
Update content on homepage hero, about, and contact

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**185**](https://github.com/MarianaSouza/web-dev-path/issues/185) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
I did.
#### What is this change?
Updated contents in the home, about, and contact according to the file provided.
#### Were there any complications while making this change?
It took time to find where the contents exist.
#### How did you verify this change?
Checked with Chrome and Firefox.
#### When should this be merged?
After review.

### CODE REVIEW

**Review by mariana-caldas — APPROVED** [review]
LGTM! Thanks, @Satoshi-Sh !

**Review by sergiobtos — APPROVED** [review]
Looks good.

**Review by LuSilvaDeveloper — APPROVED** [review]
Everything looks good. Good job @Satoshi-Sh !

**Review by cherylli — APPROVED** [review]
looks good

**Pull request merged**
