### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by mariana-caldas**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |

#### Have you updated the CHANGELOG.md file? If not, please do it.

Yes :)

#### What is this change?

We're releasing version 1.1.0, which includes the Homepage, many new components, and the reCaptcha integration.
After merging this PR, I'll create a GitHub tag release as seen [here](https://github.com/Web-Dev-Path/web-dev-path/releases/tag/v1.0.0) with all the [CHANGELOG.md](https://github.com/Web-Dev-Path/web-dev-path/blob/master/CHANGELOG.md) data we've been adding under "Unreleased".

#### Were there any complications while making this change?

No.

#### How did you verify this change?

Locally.

#### When should this be merged?

After review.

### CODE REVIEW

**Review by cherylli — APPROVED** [review]

**Review by camille-granier — APPROVED** [review]

**Comment by Faith-Nchifor** [comment]
Hello @mariana-caldas , 
I’m a little lost here. I haven’t seen any changes on the latest deploy, so I don’t know what to comment on.
I only noticed that the recaptcha shows an error on the landing page. 
I wish to know if that is to be fixed
Thanks.

**Comment by cherylli** [comment]
> Hello @mariana-caldas , I’m a little lost here. I haven’t seen any changes on the latest deploy, so I don’t know what to comment on. I only noticed that the recaptcha shows an error on the landing page. I wish to know if that is to be fixed Thanks.

what error did you get?

**Comment by Faith-Nchifor** [comment]
> > Hello @mariana-caldas , I’m a little lost here. I haven’t seen any changes on the latest deploy, so I don’t know what to comment on. I only noticed that the recaptcha shows an error on the landing page. I wish to know if that is to be fixed Thanks.
> 
> what error did you get?

catchaerror
The  error is on the right bottom section of the landing page as higlighted on this photo

**Comment by Faith-Nchifor** [comment]
> > Hello @mariana-caldas , I’m a little lost here. I haven’t seen any changes on the latest deploy, so I don’t know what to comment on. I only noticed that the recaptcha shows an error on the landing page. I wish to know if that is to be fixed Thanks.
> 
> what error did you get?

catchaerror
The  error is on the right bottom section of the landing page as higlighted on this photo

**Comment by Faith-Nchifor** [comment]
> > > > Hello @mariana-caldas , I’m a little lost here. I haven’t seen any changes on the latest deploy, so I don’t know what to comment on. I only noticed that the recaptcha shows an error on the landing page. I wish to know if that is to be fixed Thanks.
> > > 
> > > 
> > > what error did you get?
> > 
> > 
> > catchaerror The error is on the right bottom section of the landing page as higlighted on this photo
> 
> Hi @Faith-Nchifor ! This error solution was already explained on our Slack channel. Please keep an eye on the messages to follow the project instructions properly, thanks!

Alright. I'm gonna check it out. Thanks for the reply

**Pull request merged**
