### PR TITLE
Fix robots.txt and add SEO tags

### PR DESCRIPTION
**Pull request by vmcodes**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [#206](https://github.com/MarianaSouza/web-dev-path/issues/206) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
yes

#### What is this change?
updated robots.txt to allow Google to crawl site and added SEO tags

#### Were there any complications while making this change?
no

#### When should this be merged?
after review

### CODE REVIEW

**Comment by vmcodes** [comment]
I added SEO tags to the _documents.js head, but I think we should discuss the best keywords and relevant content for the site

**Comment by Satoshi-Sh** [comment]
Is there any way to see what it looks like on the search result with the preview site?

**Review by mariana-caldas — APPROVED** [review]
LGTM, thanks, @vmcodes !

**Comment by vmcodes** [comment]
> Is there any way to see what it looks like on the search result with the preview site?



> Is there any way to see what it looks like on the search result with the preview site?

Twitter used to have a pretty cool preview tool for Twitter cards, but unfortunately I'm not sure of any others at the moment. Also, since the the logo references aren't on the main branch yet, a preview wouldn't work since we reference the full path. That would be really useful though.

**Comment by vmcodes** [comment]
> LGTM, thanks, @vmcodes !



> LGTM, thanks, @vmcodes !

@mariana-caldas no problem, any suggestions for the keys words and descriptions located in the _document.js head section?

**Comment by mariana-caldas** [comment]
> > LGTM, thanks, @vmcodes !
> 
> @mariana-caldas no problem, any suggestions for the keys words and descriptions located in the _document.js head section?

I've just created this issue to tackle that on `Meta.js` -> https://github.com/Web-Dev-Path/web-dev-path/issues/208 . I wonder if that's enough or if we should use a similar approach of getting that data dynamically from `meta.js` later to add the data dynamically according to the page router @Satoshi-Sh and @vmcodes

**Comment by mariana-caldas** [comment]
> > > LGTM, thanks, @vmcodes !
> > 
> > 
> > @mariana-caldas no problem, any suggestions for the keys words and descriptions located in the _document.js head section?
> 
> I've just created this issue to tackle that on `Meta.js` -> #208 . I wonder if that's enough or if we should use a similar approach of getting that data dynamically from `meta.js` later to add the data dynamically according to the page router @Satoshi-Sh and @vmcodes

I actually asked chatGPT about the possible redundancy of adding meta tags both on `_documents.js` and on `Meta.js` and that was the answer. So I guess we can just move forward and work with dynamic data later on the #208 issue. Please let me know your thoughts!

Screen Shot 2023-11-19 at 6 19 42 PM

**Review by Satoshi-Sh — APPROVED** [review]
Let's see what will happen in production.  Thanks for your work!!

**Comment by vmcodes** [comment]
> Let's see what will happen in production. Thanks for your work!!

Expect a delay in the images populating as far as the meta tags for social media go because they do occasionally take some time, but I think we'll be alright once they do.

**Review by cherylli — APPROVED** [review]

**Pull request merged**
