### PR TITLE
Added sitemap

### PR DESCRIPTION
**Pull request by vmcodes**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [167](https://github.com/Web-Dev-Path/web-dev-path/issues/167) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
yes

#### What is this change?
adding a dynamic sitemap.xml

#### Were there any complications while making this change?
no

#### How did you verify this change?
verified the url displayed all the site links, as well as made sure the site built without errors

#### When should this be merged?
anytime

### CODE REVIEW

**Review by mariana-caldas — CHANGES_REQUESTED** [review]
That's a great job, @vmcodes! Thanks for your proactivity!

In Next.js, the `getServerSideProps` function is the one responsible for generating the dynamic content for the page. The `SiteMap` function is not necessary in this case because it doesn't render any content on the page. Can you please remove it?

**Comment by vmcodes** [comment]
@mariana-caldas I removed the last modified tags to match the dynamically created sitemap urls. However, I'm receiving this error message when removing the SiteMap function.

image

**Comment by cherylli** [comment]
works fine for me, but there are some conflicts to resolve.

**Comment by vmcodes** [comment]
> works fine for me, but there are some conflicts to resolve.

Conflicts should be resolved now, thank you.

**Review by cherylli — APPROVED** [review]
looks good

**Review by bernardoasc — APPROVED** [review]
Thank you! Everything looks great!

**Review by mariana-caldas — APPROVED** [review]
LG(reat)TM! Thanks, @vmcodes

**Pull request merged**
