### PR TITLE
Fix invalid next.config.js due to changes in newer next.js version

### PR DESCRIPTION
**Pull request by cherylli**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**169**](https://github.com/MarianaSouza/web-dev-path/issues/169) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
yes

#### What is this change?
fix invalid next.config.js warnings due to changes in a newer next.js version
- update next-pwa to 5.6
- remove compiler options for styled-components (it was actually not needed)

#### Were there any complications while making this change?
no

#### How did you verify this change?
run locally

#### When should this be merged?
after review

### CODE REVIEW

**Comment by mariana-caldas** [comment]
Great job, @cherylli ! The warning is gone on my end! 🎉 

When you go to the blog page, do you also see this error related to the Tag styling? I wonder if it's caused by the missing styled-components options we're removing.

image

**Comment by cherylli** [comment]
Now I remember why we need the styled-components in the config, it's needed for SSR mostly which we use in the blog page. I might try to use another way so we don't see the warning

**Comment by cherylli** [comment]
it should run without error now but when/if we ever going to migrate to the new next.js app structure, we might have to redo this again, as they have another method in the beta docs

**Review by mariana-caldas — APPROVED** [review]
Nice and clean, @cherylli ! Great job! 🥇

**Review by bernardoasc — APPROVED** [review]
Everything Running smoothly on my side! Thank you for Fixing that!

**Comment by cherylli** [comment]
- [x] fixed some typos in changelog, 
- [x] removed some unused and duplicate imports/exports
- [x] changed position of the bracket in contact page where it covers the text in certain width/height combination

**Pull request merged**
