### PR TITLE
Feature/add decorations

### PR DESCRIPTION
**Pull request by vmcodes**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [77](https://github.com/Web-Dev-Path/web-dev-path/issues/77) |

#### Have you updated the CHANGELOG.md file? If not, please do it.

Yes.

#### What is this change?

Adding decoration components YellowBracket.js and BlueStick.js. 
Updated to Bracket.js and Stick.js due to default props added for fill. Also, I added the components to the homepage along with the missing TwoColumn.js component to allow for a preview of the positioning of these components.

Please see the Netlify preview when possible.

#### Were there any complications while making this change?

The svg colors are unable to be changed directly via scss, so the Image component provided by Next JS appears to not be the best option in this case. I added an optional 'fill' prop that has a default value of the original fill color. However, the className prop works as expected when a class is passed through as a prop.

#### How did you verify this change?

Tested locally with different scss values and props. The lack of a prop had no negative effects, but did show that the svg could be modified. Different scss values passed through the className prop also worked as expected for positioning and changing height/width.

#### When should this be merged?

Before committing I pulled from master, so this branch should be ready to be merged after review.

### CODE REVIEW

**Comment by mariana-caldas** [comment]
I'm converting this PR as Draft because it seems it wasn't created from the most updated master, the version that has the "Nonprofit section". As soon as you have it solved, @vmcodes , could you please click over "Ready for review", assign yourself for this PR, and request reviews?

**Comment by vmcodes** [comment]
> 

I did pull from master first before pushing the recent commits.

**Comment by mariana-caldas** [comment]
> @mariana-caldas I did pull from master first before pushing the recent commits, please see the Netlify deploy preview.

Your CHANGELOG file said otherwise, @vmcodes  -> it did not include the previous feature information and I found it intriguing. 
Also, there are more details we talked about on Slack that make this PR incomplete for review. Please only request reviews when your PR is completely ready, does that make sense? Please let me know if you need help to implement the other remaining changes. Thanks!

**Review by mariana-caldas — APPROVED** [review]
This PR is great, @vmcodes !
Your careful approach with the issue instructions and the fact you leverage the use of the TwoColumn.js component to position the new decoration components is impressive! Great job! 🚀

**Pull request merged**
