### PR TITLE
Adding "who we are" section to about us page

### PR DESCRIPTION
**Pull request by vmcodes**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**137**](https://github.com/Web-Dev-Path/web-dev-path/issues/137) |

#### Have you updated the CHANGELOG.md file? If not, please do it.

yes

#### What is this change?

adding the members component and who we are data

#### Were there any complications while making this change?

no

#### How did you verify this change?

locally

image

image

image

#### When should this be merged?

should be ready to merge after review

### CODE REVIEW

**Review by cherylli — COMMENTED** [review]
Looks good but I think external links should probably open in a new tab?

**Comment by klezi10** [comment]
Just wondering, does anyone know why the Netlify checks failed?

**Comment by vmcodes** [comment]
I agree about the links and updated that. I think the checks are failing because I don't have the .env file.

**Comment by cherylli** [comment]
> 

I don't think that's the issue because netlify will have its own set of .env, it shouldn't use your local env

**Comment by cherylli** [comment]
I see a couple of new errors in the console (that are not in main), not sure if they are related to the failed checks.
image

**Comment by mariana-caldas** [comment]
Hey @vmcodes ! This is looking good, man, thanks!

Could you add some styling adjustments to match the mockup and also to look better on the desktop since we will have more members added soon? I'll also need you to try reducing your description a little bit, please. The final result will be like this: 

image
image

1. Remove the white background and text shadows
2. Make the card with 20% on large screens
3. Make the images round (50% border-radius)
4. Remove the justify center to the cards grid to eft-align everything on large screens

I'm investigating the Netlify error, @vmcodes and @cherylli , but I'm afraid it is related to the payment policy for organizations that has changed. I'll get back to you! Thanks so much for pushing this 🙌🏼

**Comment by mariana-caldas** [comment]
By running `yarn build` locally @vmcodes and @cherylli , I've realized the build error is caused by the fact a folder `data` was created inside the `pages` directory with the `whoWeAre` JSON data. Apparently, Next.js doesn't like it, folks, since it expected only components to existing inside `pages`.

The way to solve that is to move the JSON `about.js` to `utils`, Vincent (attached). Please let m know if you want to try it locally and commit the changes. My suggestion is always run `yarn build locally` when you submit a PR and see any build errors 🙌🏼 

image

**Review by mariana-caldas — APPROVED** [review]
Great job on this one, @vmcodes ! 🥇 

I just have a question for you, pls. I see you copied a lot of styling code from "TwoColumn.module.css" to "Row.module.css". Is the intention here to refactor those About Us/ Homepage sections later so the custom styles live on the Row component instead? If not, can you pls remove those duplicated styles?

**Review by cherylli — APPROVED** [review]
looks good

**Comment by vmcodes** [comment]
> Great job on this one, @vmcodes ! 🥇
> 
> I just have a question for you, pls. I see you copied a lot of styling code from "TwoColumn.module.css" to "Row.module.css". Is the intention here to refactor those About Us/ Homepage sections later so the custom styles live on the Row component instead? If not, can you pls remove those duplicated styles?

Thanks for the review, I'll remove the extra styles.

**Review by mariana-caldas — APPROVED** [review]
🚀

**Review by mariana-caldas — APPROVED** [review]

**Pull request merged**
