### PR TITLE
Adjust swipeable CardsColumns.js on mobile

### PR DESCRIPTION
**Pull request by mariana-caldas**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |

#### Have you updated the CHANGELOG.md file? If not, please do it.

Yes.

#### What is this change?

We're mainly adjusting the swipeable feature CardsColumns.js on mobile. The README is also being updated to get the project ready for the next release.

#### Were there any complications while making this change?

No.

#### How did you verify this change?

Locally and by taking a look at the Netlify preview link.

adjust-slider-mobile

#### When should this be merged?

After review.

### CODE REVIEW

**Review by camille-granier — APPROVED** [review]

**Review by vmcodes — APPROVED** [review]
Looks great on mobile and any devices I could preview.

**Review by cherylli — APPROVED** [review]

**Review by Faith-Nchifor — COMMENTED** [review]
This is great. The cards are responsive and work just fine. However, I'm not so sure but I noticed the cards don't auto slide. If it doesn't slide then it's fine.

**Comment by mariana-caldas** [comment]
> This is great. The cards are responsive and work just fine. However, I'm not so sure but I noticed the cards don't auto slide. If it doesn't slide then it's fine.

Hey @Faith-Nchifor ! Yep, the idea is they only slide when the users decide so.
Also, this PR was merged some days ago. It is always more helpful when the feedback comes before the merge, so I'd recommend to follow the repo or keep an 👁️ at your email notifications to review it as soon as you see them. Thanks!

**Comment by Faith-Nchifor** [comment]
Alright. Thanks!

**Pull request merged**
