### PR TITLE
improve lighthouse scores

### PR DESCRIPTION
**Pull request by vmcodes**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [118](https://github.com/MarianaSouza/web-dev-path/issues/118) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
yes

#### What is this change?
updated images to .webp format, added robots.txt and canonical link.

#### Were there any complications while making this change?
no

#### How did you verify this change?
locally

#### When should this be merged?
after review

### CODE REVIEW

**Review by cherylli — COMMENTED** [review]
It's really hard to test if the score increases as it changes every time, especially "performance", but i've no issue running it locally.

Maybe we can work on SEO and Accessibility. Can't do much about the "learn more" but we could add some alt text maybe
[](https://i.imgur.com/eOVF9kJ.png)
[](https://i.imgur.com/eIM1pVI.png)

**Comment by vmcodes** [comment]
@cherylli Thank you for the review, I'm not exactly sure how to update the link descriptive text issue, but I'll double check the other issues that still exist. I image some may due to the preview not being the actual site page.

**Comment by cherylli** [comment]
I run it again and it's not showing some of the errors like missing alt text. I swear it shows different things every time!
I don't think we can do much about a "descriptive link" as the link is "Learn more" and lighthouse thinks it's not descriptive.

**Review by cherylli — APPROVED** [review]
Looks good. Good improvements. Don't think we can ever get to 100 as the score varies too much every time I run it

**Review by mariana-caldas — APPROVED** [review]
Such a great job as always, @vmcodes ! Thank so much! 🚀

**Pull request merged**
