### PR TITLE
Added Tony to the about page

### PR DESCRIPTION
**Pull request by tonykieling**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |

#### Have you updated the CHANGELOG.md file? If not, please do it.
Yes.

#### What is this change?
Added Tony to the About page.

#### Were there any complications while making this change?
No.

#### How did you verify this change?
With web browser.

#### When should this be merged?
After review.

### CODE REVIEW

**Review by mariana-caldas — APPROVED** [review]
Way to go, @tonykieling !

**Review by klezi10 — APPROVED** [review]

**Review by Satoshi-Sh — APPROVED** [review]
Looks good. I liked the hamburger icon on your portfolio :+1:

**Review by cherylli — APPROVED** [review]
Looks good

**Comment by tonykieling** [comment]
> Looks good. I liked the hamburger icon on your portfolio 👍

Thanks, Satoshi!

**Pull request merged**
