### PR TITLE
Adding Our Goals  & Purpose section to About Us

### PR DESCRIPTION
**Pull request by klezi10**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**123** ](https://github.com/MarianaSouza/web-dev-path/issues/123) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
Yes.

#### What is this change?
Added 'our goals' and 'our purpose' sections to about us page.

#### Were there any complications while making this change?
Yes. The CardsColumns component needs to be adjusted. 'Our goals' section is still a work in progress.

#### How did you verify this change?
Locally.

#### When should this be merged?
After adjusting CardsColumns component and after review.

### CODE REVIEW

**Comment by klezi10** [comment]
When you have some time, I'd love to get your advice on this issue @mariana-caldas @cherylli

**Comment by cherylli** [comment]
I changed CardColumn so it works with an optional image. Also the styling of the cards are in Card.module.scss
@klezi10 will continue on the styling

**Comment by mariana-caldas** [comment]
Hey @klezi10 and @cherylli !
OMG, you both make such a great team, eh? Great job on this one!

I've recorded [this video ](https://www.loom.com/share/236f1e9b3f474677a4727d90b0b0131e)detailing my feedback, please let me know if it makes sense. Thanks!

**Comment by cherylli** [comment]
yeah i agree how you render the card looks better 👍. But I believe they produce the same effect. the Card component will still receive undefined for any non specified props.

Links should also be optional, like in this case there's no link required, but i think is Kles already onto it

**Comment by klezi10** [comment]
I just changed the ternary for link and linkText - thank you @mariana-caldas @cherylli !
The video is really great for understanding by having a visual - better than text in my opinion. I will work on the custom class next.

**Review by mariana-caldas — APPROVED** [review]
I've just adjusted some final styling referent to that new `customClass` property -that had to be passed to `CardsColumns` too in order to work since that's the component rendered on `about.js` (lines 98-105) and I think it is ready to go @klezi10 . Please let me know if all that makes sense to you.
Great job on this one! 🚀

**Review by cherylli — APPROVED** [review]
Looks good. 
something really minor, on the left and right edge the shadow is cut off, i guess there's not enough space. I guess just because there's not enough padding
[](https://i.imgur.com/Ijbxmb8.png)

**Comment by klezi10** [comment]
Is this what you mean @cherylli ? To compare, I gave the cards a margin-left and it looks different than margin-right of the right card.

`//About Us
  &.our-goals {
    ...
    margin-left: 1.5rem;`

[](https://i.imgur.com/wPvyoki.jpg)

I also made the edits to the homepage cards - margin-left of the left card vs margin-right of the far right card.

[](https://i.imgur.com/uFD6l3k.jpg)

What do you think @mariana-caldas ?

**Comment by cherylli** [comment]
> 

I mean this edge which is on both left and right, The shadow part is cut off. I only put padding-left to test but should add a padding-right as well. I'm not sure if this is something people would actually notice

[](https://i.imgur.com/TpK5va7.png)

**Review by Schlickmann — APPROVED** [review]

**Comment by mariana-caldas** [comment]
> > 
> 
> I mean this edge which is on both left and right, The shadow part is cut off. I only put padding-left to test but should add a padding-right as well. I'm not sure if this is something people would actually notice
> 
> [](https://i.imgur.com/TpK5va7.png)

Why don't you try to implement the padding-right to the component globally and, then, you decide if that box shadow looks better on the cards both on the homepage and about us? I'd only recommend to test that on mobile too @cherylli and @klezi10  🙌🏼

**Review by mariana-caldas — APPROVED** [review]
LGreatTM! Thanks for putting a lot of attention to detail on this one 🚀

**Comment by klezi10** [comment]
I made adjustments so the smallest screen size in the market (350px) is included and the cards look good, both in the homepage and in the about page. Once I have your thumbs up on the last commit, I will go ahead and merge. Thanks for your help @cherylli  and @mariana-caldas

**Review by cherylli — APPROVED** [review]
works perfectly

**Pull request merged**
