### PR TITLE
Enhance Blog Page: Add Section for Success Stories

### LINKED ISSUE #192: Enhance Blog Page: Add Section for Success Stories
**What do we need to build or fix?**
We want to enhance our [blog page](https://www.webdevpath.co/blog) by adding a new section that prominently displays blog posts with the `webdevpathsuccess` tag. This section should be positioned just below the "Latest Posts" section and will be dedicated to showcasing the success stories of collaborators who have achieved project success through Web Dev Path.

**Technical details**
We need to update our existing [blogCategories.js](https://github.com/Web-Dev-Path/web-dev-path/blob/main/utils/blogCategories.js) file to incorporate the new success stories section. This involves adding the necessary properties to recognize and handle the `webdevpathsuccess` tag, title, and path.

**Approach suggestions**
Update our existing [blogCategories.js](https://github.com/Web-Dev-Path/web-dev-path/blob/main/utils/blogCategories.js) with the following info:

_path_: tag: 'webdevpathsuccess' 
_heading_: 'Our success stories'

**Deadline**
Please keep in mind that once you assign this task to yourself, you'll need to complete it in 7 days.

**Acceptance criteria**

- Test the section and components in many screen sizes, you can use the Inspect tool for that.
- Please test if the new changes added to the components do not affect the other instances.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- If there are any build problems when submitting your PR, run `yarn build` locally to solve the issues and commit the changes.
- Update the `CHANGELOG.md` file.

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**192**](https://github.com/MarianaSouza/web-dev-path/issues/192) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
I did.
#### What is this change?
Added a section for success stories to the blog page.
#### Were there any complications while making this change?
No.
#### How did you verify this change?
Tested locally on my browser.
#### When should this be merged?
After reviewing.

closes #192

### CODE REVIEW

**Review by cherylli — APPROVED** [review]
works fine for me locally

**Comment by cherylli** [comment]
@mariana-caldas do you think Next.js and Typescript should be removed as highlighted topics? I'm not sure if it's something we want to highlight over other topics, I just had those in for testing because they were all we had back then

**Review by mariana-caldas — APPROVED** [review]
LGTM! Thanks, @Satoshi-Sh !

**Review by LuSilvaDeveloper — APPROVED** [review]
Looks good!

**Pull request merged**
