### PR TITLE
Google Analytics 4 integration with next script

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**181**](https://github.com/MarianaSouza/web-dev-path/issues/181) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
Yes.
#### What is this change?
Using next/script instead o the next-ga library. Fixed CHANGELOG.md.
#### Were there any complications while making this change?
No.
#### How did you verify this change?
Checked if datayLayer is defined in the browser terminal. 
#### When should this be merged?
After review

### CODE REVIEW

**Comment by cherylli** [comment]
Just checking, is this still a draft or ready to review?

**Comment by Satoshi-Sh** [comment]
It's ready to review.  Thanks for the headsup.

**Review by cherylli — APPROVED** [review]
I can confirm the code is working, using my own GA account from localhost
image

**Review by mariana-caldas — APPROVED** [review]
Looks great to me! Thanks, @Satoshi-Sh ! 🚀

**Review by LuSilvaDeveloper — APPROVED** [review]
Looks good to me! Good job @Satoshi-Sh

**Pull request merged**
